name: paylink
description: paylink app
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.4.0+1

environment:
  sdk: ">=3.5.4 <4.2.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  # manually added dependency
  get: 4.6.6
  flutter_screenutil: 5.9.3
  google_fonts: 6.2.1
  font_awesome_flutter: 10.7.0
  country_code_picker: ^3.0.0
  material_design_icons_flutter: 7.0.7296
  get_storage: ^2.0.3
  logger: 2.3.0
  pin_code_fields: 8.0.1
  intl: ^0.18.0
  image_picker: 1.1.2
  dotted_line: ^3.1.0
  flutter_svg:
  iconsax: ^0.0.8
  qr_flutter: ^4.1.0
  flutter_animate: 4.5.0
  dotted_border: 2.1.0
  chart_sparkline: 1.0.15+1
  flutter_inappwebview: 6.0.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  connectivity_plus: 5.0.1
  http: 1.2.1
  r_dotted_line_border: ^0.1.1
  flutter_html: ^3.0.0-beta.2
  syncfusion_flutter_pdfviewer:
  path_provider: 2.1.3
  file_picker: 8.0.3
  permission_handler: 11.3.1
  dropdown_button2: ^2.3.9
  url_launcher: 6.3.0
  win32: ^5.5.4
  dynamic_languages:
    git:
      url: https://github.com/appdevsx/dynamic_languages
      ref: main
  restart_app: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 4.0.0
  flutter_launcher_icons: 0.13.1
  #  flutter_app_name: ^0.1.0
  change_app_package_name: 1.2.0
  build_runner:
  flutter_gen_runner:

flutter_app_name:
  name: "PayLink"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app-launcher.png"

flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/clipart/
    - assets/icon/
    - assets/logo/
